using System.Text.Json.Serialization;

namespace NetScad.Core.Measurements
{
    public class Colors
    {
        public enum OpenScadColor
        {
            [JsonInclude]
            AliceBlue,
            [JsonInclude]
            AntiqueWhite,
            [JsonInclude]
            Aqua,
            [JsonInclude]
            Aquamarine,
            [JsonInclude]
            Azure,
            [JsonInclude]
            Beige,
            [JsonInclude]
            Bisque,
            [JsonInclude]
            Black,
            [JsonInclude]
            BlanchedAlmond,
            [JsonInclude]
            Blue,
            [JsonInclude]
            BlueViolet,
            [JsonInclude]
            Brown,
            [JsonInclude]
            BurlyWood,
            [JsonInclude]
            CadetBlue,
            [JsonInclude]
            Chartreuse,
            [JsonInclude]
            Chocolate,
            [JsonInclude]
            Coral,
            [JsonInclude]
            CornflowerBlue,
            [JsonInclude]
            Cornsilk,
            [JsonInclude]
            Crimson,
            [JsonInclude]
            Cyan,
            [JsonInclude]
            DarkBlue,
            [JsonInclude]
            DarkCyan,
            [JsonInclude]
            DarkGoldenRod,
            [JsonInclude]
            DarkGray,
            [JsonInclude]
            DarkGrey,
            [JsonInclude]
            DarkGreen,
            [JsonInclude]
            DarkKhaki,
            [JsonInclude]
            DarkMagenta,
            [JsonInclude]
            DarkOliveGreen,
            [JsonInclude]
            DarkOrange,
            [JsonInclude]
            DarkOrchid,
            [JsonInclude]
            DarkRed,
            [JsonInclude]
            DarkSalmon,
            [JsonInclude]
            DarkSeaGreen,
            [JsonInclude]
            DarkSlateBlue,
            [JsonInclude]
            DarkSlateGray,
            [JsonInclude]
            DarkSlateGrey,
            [JsonInclude]
            DarkTurquoise,
            [JsonInclude]
            DarkViolet,
            [JsonInclude]
            DeepPink,
            [JsonInclude]
            DeepSkyBlue,
            [JsonInclude]
            DimGray,
            [JsonInclude]
            DimGrey,
            [JsonInclude]
            DodgerBlue,
            [JsonInclude]
            FireBrick,
            [JsonInclude]
            FloralWhite,
            [JsonInclude]
            ForestGreen,
            [JsonInclude]
            Fuchsia,
            [JsonInclude]
            Gainsboro,
            [JsonInclude]
            GhostWhite,
            [JsonInclude]
            Gold,
            [JsonInclude]
            GoldenRod,
            [JsonInclude]
            Gray,
            [JsonInclude]
            Grey,
            [JsonInclude]
            Green,
            [JsonInclude]
            GreenYellow,
            [JsonInclude]
            HoneyDew,
            [JsonInclude]
            HotPink,
            [JsonInclude]
            IndianRed,
            [JsonInclude]
            Indigo,
            [JsonInclude]
            Ivory,
            [JsonInclude]
            Khaki,
            [JsonInclude]
            Lavender,
            [JsonInclude]
            LavenderBlush,
            [JsonInclude]
            LawnGreen,
            [JsonInclude]
            LemonChiffon,
            [JsonInclude]
            LightBlue,
            [JsonInclude]
            LightCoral,
            [JsonInclude]
            LightCyan,
            [JsonInclude]
            LightGoldenRodYellow,
            [JsonInclude]
            LightGray,
            [JsonInclude]
            LightGrey,
            [JsonInclude]
            LightGreen,
            [JsonInclude]
            LightPink,
            [JsonInclude]
            LightSalmon,
            [JsonInclude]
            LightSeaGreen,
            [JsonInclude]
            LightSkyBlue,
            [JsonInclude]
            LightSlateGray,
            [JsonInclude]
            LightSlateGrey,
            [JsonInclude]
            LightSteelBlue,
            [JsonInclude]
            LightYellow,
            [JsonInclude]
            Lime,
            [JsonInclude]
            LimeGreen,
            [JsonInclude]
            Linen,
            [JsonInclude]
            Magenta,
            [JsonInclude]
            Maroon,
            [JsonInclude]
            MediumAquaMarine,
            [JsonInclude]
            MediumBlue,
            [JsonInclude]
            MediumOrchid,
            [JsonInclude]
            MediumPurple,
            [JsonInclude]
            MediumSeaGreen,
            [JsonInclude]
            MediumSlateBlue,
            [JsonInclude]
            MediumSpringGreen,
            [JsonInclude]
            MediumTurquoise,
            [JsonInclude]
            MediumVioletRed,
            [JsonInclude]
            MidnightBlue,
            [JsonInclude]
            MintCream,
            [JsonInclude]
            MistyRose,
            [JsonInclude]
            Moccasin,
            [JsonInclude]
            NavajoWhite,
            [JsonInclude]
            Navy,
            [JsonInclude]
            OldLace,
            [JsonInclude]
            Olive,
            [JsonInclude]
            OliveDrab,
            [JsonInclude]
            Orange,
            [JsonInclude]
            OrangeRed,
            [JsonInclude]
            Orchid,
            [JsonInclude]
            PaleGoldenRod,
            [JsonInclude]
            PaleGreen,
            [JsonInclude]
            PaleTurquoise,
            [JsonInclude]
            PaleVioletRed,
            [JsonInclude]
            PapayaWhip,
            [JsonInclude]
            PeachPuff,
            [JsonInclude]
            Peru,
            [JsonInclude]
            Pink,
            [JsonInclude]
            Plum,
            [JsonInclude]
            PowderBlue,
            [JsonInclude]
            Purple,
            [JsonInclude]
            RebeccaPurple,
            [JsonInclude]
            Red,
            [JsonInclude]
            RosyBrown,
            [JsonInclude]
            RoyalBlue,
            [JsonInclude]
            SaddleBrown,
            [JsonInclude]
            Salmon,
            [JsonInclude]
            SandyBrown,
            [JsonInclude]
            SeaGreen,
            [JsonInclude]
            SeaShell,
            [JsonInclude]
            Sienna,
            [JsonInclude]
            Silver,
            [JsonInclude]
            SkyBlue,
            [JsonInclude]
            SlateBlue,
            [JsonInclude]
            SlateGray,
            [JsonInclude]
            SlateGrey,
            [JsonInclude]
            Snow,
            [JsonInclude]
            SpringGreen,
            [JsonInclude]
            SteelBlue,
            [JsonInclude]
            Tan,
            [JsonInclude]
            Teal,
            [JsonInclude]
            Thistle,
            [JsonInclude]
            Tomato,
            [JsonInclude]
            Turquoise,
            [JsonInclude]
            Violet,
            [JsonInclude]
            Wheat,
            [JsonInclude]
            White,
            [JsonInclude]
            WhiteSmoke,
            [JsonInclude]
            Yellow,
            [JsonInclude]
            YellowGreen
        }
    }
}
