<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	  <PublishTrimmed>true</PublishTrimmed>
	  <TrimMode>link</TrimMode>
	  <SignAssembly>True</SignAssembly>
	  <Platforms>x64;ARM64</Platforms>
  </PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)'=='Release'">
		<DebugType>none</DebugType>
		<DebugSymbols>false</DebugSymbols>
	</PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|ARM64'">
    <IsTrimmable>True</IsTrimmable>
    <DebugType>none</DebugType>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
    <IsTrimmable>True</IsTrimmable>
    <DebugType>none</DebugType>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|ARM64'">
    <IsTrimmable>True</IsTrimmable>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
    <IsTrimmable>True</IsTrimmable>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <IsAotCompatible>True</IsAotCompatible>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NetGenCAD.Core\NetGenCAD.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="README.markdown">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
    <None Update="Scad\sample.scad">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
